name: CI/CD Angular to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout Code
      uses: actions/checkout@v3

    - name:  Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name:  Install Dependencies
      run: npm install

    - name:  Build Angular App
      run: npm run build -- --configuration=production

    - name:  Docker Login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin  

    - name:  Build Docker Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/angular-app:v2 .

    - name:  Push Image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/angular-app:v2
