name: Angular App CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # - name: Install Dependencies
    #   run: npm install

    # - name: Build Angular App
    #   run: npm run build --prod

    # - name: Docker Login
    #   run: echo "dckr_pat_WJbL2-fjF86XdcDWvSd-SNoy4pg" | docker login -u "bitaouioussama" --password-stdin  

    # - name: Build Docker Image
    #   run: docker build -t bitaouioussama/angular-app:v2 .

    # - name: Push Image to DockerHub
    #   run: docker push bitaouioussama/angular-app:v2

    - name: Start Minikube
      run: minikube start --driver=docker

    - name: Set kubectl context to Minikube
      run: kubectl config use-context minikube

    - name: Wait for Kubernetes to be ready
      run: |
        for i in {1..10}; do
          kubectl get nodes && break || sleep 10
        done

    - name: Apply Kubernetes Deployment
      run: kubectl apply -f configfile.yaml
