name: Docker Login Test

on:
  workflow_dispatch:

jobs:
  test-login:
    runs-on: self-hosted
    steps:
      - name: Docker login test
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
