name: Build Angular Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.10.0

      - name: Install Dependencies
        run: |
          npm install
          npm install primeflex primeicons --legacy-peer-deps

      - name: Build Angular App
        run: npm run build
